
# Pictures
# TCI
# barplot_profiling_tci_first:
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/basic_bm/tci.pkl -bm swo_bench -ucol storage operation -fs DVS_POL:0 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx CNT_TYPE -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM operation:storage:FREQ:CNT_TYPE -bap 1 storage operation -xal "Counter Type" -yal "Profiling Counter / Cycles" --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_tci -pfs 12 6 -fr CNT_TYPE:0

#lineplot_fws_freq_dvspol
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/tci.pkl -bm swo_bench -ucol storage operation -fs CNT_TYPE:0 operation:0 storage:0 -col FWS -idx FREQ -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV DVS_POL?0:LOW_VOLTAGE?1:FAST_FLASH -repst CNT_NORM FREQ:DVS_POL -lp 0 DVS_POL DVS_MV -xal "CPU Frequency [Hz]" -yal "Flash Wait States" "CPU Voltage [mV]"  -pfs 12 4 -ltl "Flash Wait States" "Voltage" --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic lineplot_fws_freq_dvspol

# barplot_profiling_tci:
#python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/tci.pkl -bm swo_bench -ucol storage operation -fs DVS_POL:1 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM operation:storage:FREQ:CNT_TYPE -bap 1 operation:CNT_TYPE -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -csc CNT_NORM 10000 div -ltl "Counter Type" "Operation Type" -ccl -legl 0.01:0.6 0.85:0.7 --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_ffpol_tci

python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/tci.pkl -bm swo_bench -ucol storage operation -fs DVS_POL:0 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM operation:storage:FREQ:CNT_TYPE -bap 1 operation:CNT_TYPE -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_lvpol_tci

# barplot_profiling_tci_freq: ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/tci.pkl -bm swo_bench -ucol operation storage  -fs operation:0 DVS_POL:1 -col CNT_NORM_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV DVS_POL?0:LOW_VOLTAGE?1:FAST_FLASH -repst CNT_NORM operation:storage:FREQ:CNT_TYPE:DVS_POL -bap 1 FREQ:CNT_TYPE -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl -csc CNT_NORM 10000 div  --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_tci_freq


# barplot_cycles_tci_freq ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/tci.pkl -bm swo_bench -ucol operation storage  -fs operation:0 DVS_POL:1 -col CYC_DIFF_PROP_DIV -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV DVS_POL?0:LOW_VOLTAGE?1:FAST_FLASH -repst CNT_NORM operation:storage:FREQ:CNT_TYPE:DVS_POL -fsp CNT_TYPE:1 -bap 1 FREQ -xal "Access Type" -yal "Cycles / Cycles (80MHz)"  -pfs 12 4 -fr CNT_TYPE:0  --legend-loc 1.01:0.57 -ccl -prop div CYC_DIFF FREQ:80000000 storage:CNT_TYPE -an "4 MCycles":-0.1:1 "376 MCycles":0.9:1 "483 MCycles":1.9:1 -ltl "CPU Frequency [MHz]" --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_cycles_tci_freq_same_iter

# barplot_profiling_raw_tci_ffpol_80_same_iter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/questions/compare_same_iterations/nucleo-l476rg/swo_bench/tci.pkl -bm swo_bench -ucol storage operation -fs FREQ:80000000 -col CNT_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM:CNT operation:storage:FREQ:CNT_TYPE -bap 1 operation CNT_TYPE -xal "Access Type" -yal "Profiling Counter [#]" -pfs 12 4 -fr CNT_TYPE:0 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_profiling_raw_tci_ffpol_80_same_iter

# barplot_ram_flash_tci_ffpol_80 ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/merged_cnt_type/basic_bm/tci.pkl -bm swo_bench -ucol storage operation -fs FREQ:80000000 DVS_POL:1 -col CNT_NORM -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV  -bap 1 operation:CNT_TYPE -xal "Access Type" -yal "Comparator Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -fsp CNT_TYPE}5 -csc2 CNT_REP_STD 8.25 div CNT_STD_NORM -cc CNT_STD_NORM CNT_STD_NORM CYC_DIFF div -errcol CNT_STD_NORM -csc CNT_NORM 10000 div -ltl "Counter Type" "Operation Type" -ccl -legl 0.01:0.7 0.01:0.4 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_tci_ffpol_80


# barplot_profiling_tci_ffpol_80_same_iter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/questions/compare_same_iterations/nucleo-l476rg/swo_bench/tci.pkl -bm swo_bench -ucol storage operation -fs FREQ:80000000 -col CNT_NORM_REP_MEAN -idx storage -repst CNT_NORM operation:storage:FREQ:CNT_TYPE -bap 1 operation:CNT_TYPE  -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -csc CNT_NORM 10000 div -ltl "Counter Type" "Operation Type" -ccl -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -legl 0.01:0.6 0.85:0.7 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_tci_ffpol_80_same_iter

# barplot_profiling_tci_ffpol_80_same_iter_flash_cache
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/no_cache/code_restructure/basic_bm/seperately_diabled/nucleo-l476rg/swo_bench/merged/tci_mixed_cache.pkl -bm swo_bench -fs DVS_POL:1 CNT_TYPE:2 storage:2 -col CNT_NORM -fsp FREQ:80000000  -col CNT_NORM -bap 1 FLASH_CACHE -idx operation -ccl -cl operation?0:ADD?1:MUL?2:DIV -yal "Profiling Counter / Cycles" -xal "Operation Type" -pfs 15 3 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_tci_ffpol_80_same_iter_flash_cache

# barplot_profiling_tci_ffpol_80_same_iter_flash_cache_raw
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/no_cache/code_restructure/basic_bm/seperately_diabled/nucleo-l476rg/swo_bench/merged/tci_mixed_cache.pkl -bm swo_bench -fs DVS_POL:1 CNT_TYPE:2 storage:2 -col CNT_NORM -fsp FREQ:80000000  -col CNT_REP_MEAN -bap 1 FLASH_CACHE -idx operation -ccl -cl operation?0:ADD?1:MUL?2:DIV -yal  "Raw Counter [#]" -xal "Operation Type" -pfs 15 3 -legl 0.6:0.6 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_tci_ffpol_80_same_iter_flash_cache_raw

# TCI_FLOAT
#python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/nucleo-l476rg/swo_bench/tci_float.pkl -bm swo_bench -ucol storage operation -fs DVS_POL:1 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM operation:storage:FREQ:CNT_TYPE:DVS_POL -bap 1 operation:CNT_TYPE -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -ccl


# TCI_DOUBLE
#python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/nucleo-l476rg/swo_bench/tci_double.pkl -bm swo_bench -ucol storage operation -fs DVS_POL:1 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx storage -cl storage?0:REG?1:RAM?2:FLASH operation?0:ADD?1:MUL?2:DIV -repst CNT_NORM operation:storage:FREQ:CNT_TYPE:DVS_POL -bap 1 operation:CNT_TYPE -xal "Access Type" -yal "Profiling Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 -ccl


# SPI
# barplot_profiling_lvpol_spi:
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:0 -col CNT_NORM_REP_MEAN -idx spifreq -repst CNT_NORM spifreq:FREQ:CNT_TYPE -bap 0 CNT_TYPE:FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Profiling Counter / Cycles"  -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_lvpol_spi

# barplot_profiling_ffpol_spi ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 -col CNT_NORM_REP_MEAN -idx spifreq -repst CNT_NORM spifreq:FREQ:CNT_TYPE -bap 0 CNT_TYPE:FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Profiling Counter / Cycles"  -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl -csc CNT_NORM 10000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_ffpol_spi

# barplot_cycles_ffpol_spi_same_iter ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/comparator/FLASH/basic_bm/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 CNT_TYPE:100 -col CYC_DIFF_REP_MEAN -idx spifreq -repst CYC_DIFF spifreq:FREQ:CNT_TYPE -bap 1 FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Cycles [#]" -ltl "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_cycles_ffpol_spi_same_iter

# barplot_cycles_ffpol_spi_same_iter_nofwsa ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/no_fwsa/code_restructure/basic_bm//nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 -col CYC_DIFF_REP_MEAN -idx spifreq -repst CYC_DIFF spifreq:FREQ:CNT_TYPE -bap 1 FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Cycles [#]" -ltl "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_cycles_ffpol_spi_same_iter_nofwsa

# barplot_ram_flash_ffpol_spi_sameiter ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/spi.pkl -bm swo_bench -ucol DVS_POL:spifreq  -col CNT_NORM -idx spifreq -bap 1 FREQ:CNT_TYPE -fs DVS_POL:1  -xal "Selected SPI Frequency [Hz]" -yal "Comparator Counter / Cycles"  -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000  --legend-loc 1.01:0.57 1.01:0.1 -ro CNT_REP_MEAN DVS_POL:FREQ:spifreq sum CNT_TYPE:100:101:102 100 -csc2 CNT_REP_MEAN 8.25 div CNT_NORM -cc CNT_NORM CNT_NORM CYC_DIFF div -ltl "Counter Type" "CPU Frequency [MHz]" -ccl --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_spi_sameiter

# # barplot_spi_cycles
# python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:0 CNT_TYPE:2 -col CYC_DIFF -idx spifreq -repst CNT_NORM spifreq:FREQ:CNT_TYPE -bap 1 FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Cycles [#]" -ltl "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_spi_cycles

# lineplot_cyclespeedup_spi
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -cl DVS_POL?0:LOW_VOLTAGE?1:FAST_FLASH -ucol spifreq DVS_POL  -col FREQ -prop div CYC_DIFF  FREQ:80000000 spifreq:DVS_POL -idx CYC_DIFF_PROP_DIV -lp spifreq:DVS_POL -fs CNT_TYPE:0 -fr spifreq:100000 -pfs 12 4 -yal "CPU Frequency [Hz]" -xal "Cycles / Cycles (80MHz)" -ltl "SPI Frequencies" "DVS Policy" -repst CNT DVS_POL:FREQ:spifreq:CNT_TYPE -xalim 0:1.1 0:1.1 0:1.1 0:1.1 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ lineplot_cyclespeedup_spi

# barplot_spi_cycles_same_iter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/comparator/FLASH/basic_bm/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:0 -col CYC_DIFF -idx spifreq -repst CNT spifreq:FREQ:CNT_TYPE -bap 1 FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Cycles [#]" -ltl "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ro CNT_REP_MEAN DVS_POL:FREQ:spifreq sum CNT_TYPE:COMP_FLASH_0:COMP_FLASH_1:COMP_FLASH_2 COMP_FLASH --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_spi_cycles_same_iter

# barplot_profiling_same_iter_raw_ffpol_spi
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 -col CNT_REP_MEAN -idx spifreq -repst CNT spifreq:FREQ:CNT_TYPE -bap 0 CNT_TYPE:FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -xal "Selected SPI Frequency [Hz]" -yal "Profiling Counter [#]" -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_same_iter_raw_ffpol_spi

# barplot_ram_flash_ffpol_spi_sameiter_raw
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 -col CNT_REP_MEAN -idx spifreq -bap 0 CNT_TYPE:FREQ -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -ro CNT_REP_MEAN DVS_POL:FREQ:spifreq sum CNT_TYPE:COMP_FLASH_0:COMP_FLASH_1:COMP_FLASH_2 COMP_FLASH -xal "Selected SPI Frequency [Hz]" -yal "Comparator Counter [#]" -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_spi_sameiter_raw

# barplot_periph_ffpol_spi_sameiter_80MHz ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench -ucol spifreq -fs DVS_POL:1 CNT_TYPE}19 FREQ:80000000 -col CNT_NORM -idx spifreq -bap 1 CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 spifreq:100000 -repst CNT DVS_POL:FREQ:spifreq:CNT_TYPE -xal "Selected SPI Frequency [Hz]" -yal "Comp. Peripheral Counter / Cycles" -ltl "Counter Type" "CPU Frequency [MHz]" --legend-loc 1.01:0.57 1.01:0.1 -csc2 CNT_REP_MEAN 8.25 div CNT_NORM -cc CNT_NORM CNT_NORM CYC_DIFF div  -ccl -als 12 --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_periph_ffpol_spi_sameiter_80MHz

# lineplot_spi_selected_actual_frequency ~
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/questions/actual_spi_freq/spi_freqs.pkl -bm trace_csv -idx actual_spifreq -col FREQ -lp selected_spifreq -pfs 12 4 -yal "CPU Frequency [MHz]" -xal "" "ACTUAL SPI FREQUENCY [MHz]" -ltl "Selected SPI\nFrequency [MHz]" -fr selected_spifreq:100000 -sg 1 3 -agr both both both -legap 2 -cl selected_spifreq?1000000:1?5000000:5?10000000:10 -ccl -csc actual_spifreq 1000000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ lineplot_spi_selected_actual_frequency



# BITBANG_GPIO
# barplot_profiling_bitbang_gpio:
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/bitbang_gpio.pkl -bm swo_bench -fs DVS_POL:0 -col CNT_NORM_REP_MEAN -idx FREQ -repst CNT_NORM FREQ:CNT_TYPE:datasize -bap 0 CNT_TYPE datasize -pfs 12 4 -fr CNT_TYPE:0  -yal "Profiling Counter / Cycles" -xal "CPU Frequency [MHz]"   -ltl "Counter Type" "Datasize" --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_lvpol_bitbang_gpio

# barplot_ram_flash_ffpol_bitbang_gpio_sameiter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/bitbang_gpio.pkl -bm swo_bench -ucol datasize -fs DVS_POL:1 -col CNT_PROP_CYC -idx FREQ -bap 0 CNT_TYPE datasize -pfs 12 4 -fr CNT_TYPE:0 -ro CNT_REP_MEAN DVS_POL:FREQ:datasize sum CNT_TYPE:COMP_FLASH_0:COMP_FLASH_1:COMP_FLASH_2 COMP_FLASH -cc CNT_PROP_CYC CNT_REP_MEAN CYC_DIFF div -xal "CPU Frequency [MHz]" -yal "Comparator Counter / Cycles" -ltl "Counter Type" "Datasize" --legend-loc 1.01:0.57 1.01:0.1 -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_bitbang_gpio_sameiter

# lineplot_cyclespeedup_bitbagng_gpio - -sg misses
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/bitbang_gpio.pkl -bm swo_bench -cl DVS_POL?0:LOW_VOLTAGE?1:FAST_FLASH -ucol datasize DVS_POL  -col CYC_DIFF_PROP_DIV -prop div CYC_DIFF  FREQ:80000000 datasize:DVS_POL -idx FREQ -lp DVS_POL:datasize -fs CNT_TYPE:0 -pfs 12 4 -xal "CPU Frequency [Hz]" -yal "Cycles / Cycles (80MHz)" -ltl "SPI Frequencies" "DVS Policy" -repst CNT DVS_POL:FREQ:datasize:CNT_TYPE  -yalim 0.9996:1.001 --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ lineplot_cyclespeedup_bitbang_gpio

# SLEEP
# barplot_profiling_sleep:
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/basic_bm/sleep.pkl -bm swo_bench -fs DVS_POL:0 -col CNT_NORM_REP_MEAN -idx FREQ -repst CNT_NORM FREQ:CNT_TYPE -bap 0 CNT_TYPE -pfs 5 3 -ccl -fr CNT_TYPE:0  -yal "Profiling Counter / Cycles" -xal "CPU Frequency [MHz]"   -ltl "Counter Type" -csc CNT_NORM 10000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_lvpol_sleep


# ADC
# barplot_profiling_adc_same_iter_80
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/adc.pkl -bm swo_bench -ucol min_sample_time_ns res_nbits -fs FREQ:80000000 DVS_POL:1 -col CNT_NORM_REP_MEAN -idx min_sample_time_ns  -repst CNT_NORM min_sample_time_ns:res_nbits:FREQ:CNT_TYPE:DVS_POL -bap 1 res_nbits CNT_TYPE -xal "Minimum Sample Time in ns" -yal "Profiling Counter / Cycles" -pfs 12 4 -fr CNT_TYPE:0 -ltl "Counter Type" "Resolution Bits" --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_adc_same_iter_80

# barplot_profiling_adc_same_iter_80_raw
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/adc.pkl -bm swo_bench -ucol min_sample_time_ns res_nbits -fs FREQ:80000000 DVS_POL:1 -col CNT_REP_MEAN -idx min_sample_time_ns  -repst CNT min_sample_time_ns:res_nbits:FREQ:CNT_TYPE:DVS_POL -bap 1 res_nbits CNT_TYPE -xal "Minimum Sample Time in ns" -yal "Profiling Counter / Cycles" -pfs 12 4 -fr CNT_TYPE:0 -ltl "Counter Type" "Resolution Bits" --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_adc_same_iter_80_raw

# barplot_ram_flash_ffpol_adc_sameiter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/adc.pkl -bm swo_bench -ucol res_nbits min_sample_time_ns -fs DVS_POL:1 FREQ:80000000 -col CNT_PROP_CYC -idx min_sample_time_ns -bap 1 res_nbits CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 -ro CNT_REP_MEAN res_nbits:min_sample_time_ns:DVS_POL:FREQ sum CNT_TYPE:COMP_FLASH_0:COMP_FLASH_1:COMP_FLASH_2 COMP_FLASH -cc CNT_PROP_CYC CNT_REP_MEAN CYC_DIFF div -xal "Minimum Sample Time in ns" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" "Resolution Bits" -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_adc_sameiter

python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/adc.pkl -bm swo_bench -ucol res_nbits min_sample_time_ns -fs DVS_POL:1 FREQ:80000000 -col CNT_REP_MEAN -idx min_sample_time_ns -bap 1 res_nbits CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 -ro CNT_REP_MEAN res_nbits:min_sample_time_ns:DVS_POL:FREQ sum CNT_TYPE:COMP_FLASH_0:COMP_FLASH_1:COMP_FLASH_2 COMP_FLASH -xal "Minimum Sample Time in ns" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" "Resolution Bits" -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_adc_sameiter_raw

# barplot_periph_ffpol_adc_sameiter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/adc.pkl -bm swo_bench -ucol res_nbits min_sample_time_ns -fs DVS_POL:1 FREQ:80000000 -col CNT_PROP_CYC -idx min_sample_time_ns -bap 1 res_nbits CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 -repst CNT res_nbits:min_sample_time_ns:FREQ:CNT_TYPE:DVS_POL -cc CNT_PROP_CYC CNT_REP_MEAN CYC_DIFF div -xal "Minimum Sample Time in ns" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" "Resolution Bits" -ccl --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_periph_ffpol_adc_sameiter

python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/adc.pkl -bm swo_bench -ucol res_nbits min_sample_time_ns -fs DVS_POL:1 res_nbits:6 CNT_TYPE:10 -col CYC_DIFF -idx min_sample_time_ns -bap 1 FREQ -pfs 12 4 -fr CNT_TYPE:0 -xal "Minimum Sample Time in ns" -yal "CYCLES" --legend-loc 1.01:0.57 1.01:0.1 -ltl "CPU Frequency [MHz]" "Counter Type" --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_cycles_ffpol_adc_res_nbits6

# SPINCRUNCH
# barplot_profiling_spincrunch_same_iter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/spincrunch.pkl -bm swo_bench -ucol work_cnt poll_us -fs DVS_POL:1 poll_us:1000000 CNT_TYPE{9 -col CNT_NORM -idx work_cnt -bap 1 FREQ:CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0  -xal "Work Counter" -yal "Profiling Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" "CPU Frequency [MHz]" -ccl --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_profiling_spincrunch_same_iter

# barplot_ram_flash_ffpol_spincrunch_same_iter
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/spincrunch.pkl -bm swo_bench -ucol work_cnt poll_us -fs DVS_POL:1 poll_us:1000000 CNT_TYPE}9 -col CNT_NORM -idx work_cnt -bap 1 FREQ:CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0  -xal "Work Counter" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" "CPU Frequency [MHz]" -ccl --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_ram_flash_ffpol_spincrunch_same_iter

# lineplot_cyclespeedup_spincrunch - -sg misses
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/spincrunch.pkl -bm swo_bench -ucol work_cnt poll_us -fs poll_us:1000000 CNT_TYPE:1 -idx CYC_DIFF_PROP_DIV -col FREQ -lp DVS_POL:work_cnt -pfs 12 4 -fr CNT_TYPE:0  -xal "Cycles / Cycles (80MHz)" "Cycles / Cycles (80MHz)" -yal "CPU Frequency [Hz]" --legend-loc 1.01:0.57 1.01:0.1 -ltl "DVS_POL" "Work Counter" -ccl -prop div CYC_DIFF FREQ:80000000 work_cnt:poll_us:DVS_POL -swap -sg 1 2 -legap 1 -agr both both --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ lineplot_cyclespeedup_spincrunch

# barplot_periph_spincrunch_ffpol_80MHz
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/spincrunch.pkl -bm swo_bench -ucol poll_us work_cnt DVS_POL -fs DVS_POL:1 FREQ:80000000 poll_us:1000000 -col CNT_NORM -idx work_cnt -bap 1 CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 -repst CNT poll_us:work_cnt:FREQ:CNT_TYPE:DVS_POL -xal "Work Counter" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" -ccl -csc2 CNT_REP_MEAN 8.25 div CNT_NORM -csc3 CNT_NORM 10000 mul CNT_NORM -cc CNT_NORM CNT_NORM CYC_DIFF div --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic/ barplot_periph_spincrunch_ffpol_80MHz

# PERIPH_MERGE

# Merge Command
#python3 /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_merge.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/adc.pkl /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/spi.pkl -bm swo_bench swo_bench -o /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/ spi_adc_merge -repst CNT CNT_TYPE:FREQ:DVS_POL -fl

python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/iter_mode_unique/nucleo-l476rg/comparator/PERIPH/nucleo-l476rg/swo_bench/spi_adc_merge.pkl -bm swo_bench -ucol BENCH -fs DVS_POL:1 FREQ:80000000 -col CNT_PROP_CYC -idx BENCH -bap 1 CNT_TYPE -pfs 12 4 -fr CNT_TYPE:0 -cc CNT_PROP_CYC CNT_REP_MEAN CYC_DIFF div -xal "Task" -yal "Comparator Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" -xatr 45 -ccl --save ~/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_periph_ffpol_80MHz_adc_spi

# CTX_SWITCH

# barplot_profiling_ctxswitch
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/ctx_switch.pkl -bm swo_bench -fs DVS_POL:1 -col CNT_NORM_REP_MEAN -idx FREQ -bap 1 CNT_TYPE -pfs 15 6 -fr CNT_TYPE:0 -xal "CPU Frequency [Hz]" -yal "Profiling Counter / Cycles" --legend-loc 1.01:0.57 1.01:0.1 -ltl "Counter Type" -repst CNT_NORM FREQ:CNT_TYPE:DVS_POL -ccl -csc CNT_NORM 10000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_profiling_ctxswitch

# barplot_profiling_ctxswitch_ffpol_80MHz
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/ctx_switch.pkl -bm swo_bench -fs DVS_POL:1 FREQ:80000000 -col CNT_NORM_REP_MEAN -idx CNT_TYPE -bap 0 -pfs 15 6 -fr CNT_TYPE:0 -xal "Counter Type" -yal "Profiling Counter / Cycles"  -repst CNT_NORM FREQ:CNT_TYPE:DVS_POL -ccl -agr both -legr 0 -csc CNT_NORM 10000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_profiling_ctxswitch_ffpol_80MHz

# barplot_ramflash_ctxswitch_ffpol_80MHz
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/merged_cnt_type/ctx_switch.pkl -bm swo_bench -fs DVS_POL:1 FREQ:80000000 -col CNT_NORM -idx CNT_TYPE -bap 0 -pfs 15 6 -fr CNT_TYPE:0 -xal "Counter Type" -yal "Comparator Counter / Cycles" -ccl -agr both -legr 0 -csc CNT_NORM 10000 div --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_ramflash_ctxswitch_ffpol_80MHz


# barplot_cyclespeedup_ctxswitch
python3 ~/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/pickle_to_plot.py -p /home/tobi/RIOT_ARBEIT/flexclock_code/BA_Measurement_Utils/results_online/home/swo_bench/same_iter/nucleo-l476rg/basic_bm/nucleo-l476rg/swo_bench/ctx_switch.pkl -bm swo_bench -fs CNT_TYPE:0 -col CYC_DIFF_REP_MEAN_PROP_DIV -idx FREQ -repst CYC_DIFF FREQ:CNT_TYPE:DVS_POL -bap 1 DVS_POL -xal "CPU Frequency [Hz]" -yal "Cycles / Cycles (80MHz)"  -pfs 15 6 -ccl -prop div CYC_DIFF_REP_MEAN FREQ:80000000 DVS_POL:CNT_TYPE --save /home/tobi/RIOT_ARBEIT/Bachelor/LateX/plots/chapter_measurements/basic barplot_cyclespeedup_ctxswitch
